services:
  nextcloud:
    image: nextcloud:${NEXTCLOUD_VERSION}
    container_name: nextcloud_app
    restart: always
    ports:
      - "${HTTP_PORT}:80"
    depends_on:
      - db
      - redis
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=${ADMIN_USERNAME}
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - NEXTCLOUD_DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./nextcloud/data:/var/www/html/data # ユーザーデータ(別HDD等に設置するとよい)
      - ./nextcloud/config:/var/www/html/config # 設定ファイル
      - ./nextcloud/themes:/var/www/html/themes # カスタムテーマ
      - ./nextcloud/custom_apps:/var/www/html/custom_apps # カスタムアプリ
    networks:
      - nextcloud_network

  db:
    image: mariadb:11.4
    container_name: nextcloud_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    volumes:
      - ./mariadb:/var/lib/mysql # MariaDBのデータ
    networks:
      - nextcloud_network

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis:/data # Redisのデータ
    networks:
      - nextcloud_network

  cloudflared:
    image: cloudflare/cloudflared
    command:
      - tunnel
      - --no-autoupdate
      - run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
      - TUNNEL_TRANSPORT_PROTOCOL=http2
    restart: always
    networks:
      - nextcloud_network

networks:
  nextcloud_network:
    driver: bridge
